drop table tecnicos;
drop table clientes;
drop table tipos_documentos;
drop table piezas;
drop table ventas;


create table tipos_documentos(
    id_tipo_documento number generated by default as identity,
    nombre not null unique
);


create table tecnicos(
    documento_tecnico varchar2(15),
    id_tipo_documento number not null,
    nombres varchar2(100) not null,
    primer_apellido varchar2(50) not null,
    segundo_apellido varchar2(50) not null
);
alter table tecnicos
add constraint pk_tecnicos_identificacion primary key(documento_tecnico);
alter table tecnicos
add constraint fk_tecnicos_id_tipo_documento foreign key(id_tipo_documento) references tipos_documentos(id_tipo_documento);
/*
alter table tecnicos
add constraint ch_tecnicos_nombres check (nombres is not null);
alter table tecnicos
add constraint ch_tecnicos_primer_apellido check (primer_apellido is not null);
*/


create table clientes(
    documento_cliente varchar2(15),
    id_tipo_documento number not null,
    nombres varchar2(100) not null,
    primer_apellido varchar2(50),
    segundo_apellido varchar2(50),
    correo_electronico varchar2(100) not null,
    celular varchar2(15) not null
);
alter table clientes
add constraint pk_clientes_identificacion primary key(documento_cliente);
alter table tecnicos
add constraint fk_clientes_id_tipo_documento foreign key(id_tipo_documento) references tipos_documentos(id_tipo_documento);


/*
alter table clientes
add constraint ch_clientes_nombres check (nombres is not null);
alter table clientes
add constraint ch_clientes_primer_apellido check (primer_apellido is not null);
alter table clientes
add constraint ch_clientes_correo_electronico check (correo_electronico is not null);
alter table clientes
add constraint ch_clientes_celular check (celular is not null);
*/


/*
create table tipos (
    id_tipo number generated by default as identity,
    nombre varchar2(10) not null
);
alter table tipos
add constraint pk_tipos_id_tipo primary key(id_tipo);
insert into tipos (nombre) values ('Pieza');
insert into tipos (nombre) values ('Producto');
*/

/*
create table productos(
    id_producto varchar2(6), --EJ: PR-01
    nombre varchar2(40) not null,
    altura number(8,2) not null,
    ancho number(8,2) not null,
    largo number(8,2) not null,
    peso number(8,2) not null,
    fecha_fabricacion date,
    valor_unitario number(12,2) not null check (valor_unitario > 0),
    id_tipo number(4) not null,
    id_tecnico number not null
);
alter table productos
add constraint pk_productos_id_producto primary key(id_producto);
alter table productos
add constraint fk_productos_id_tipo foreign key(id_tipo) references TIPOS(id_tipo);

alter table productos
add constraint ch_productos_nombre check (nombre is not null);
alter table productos
add constraint fk_productos_id_tecnico foreign key(id_tecnico) references tecnicos(id_tecnico);
*/

/*
create table piezas_productos (
    id_producto varchar2(6),
    id_pieza varchar2(6)
);
alter table piezas_productos
add constraint pk_piezas_productos_id_producto_id_pieza primary key(id_producto, id_pieza);
alter table piezas_productos
add constraint fk_piezas_productos_id_producto foreign key(id_producto) references productos(id_producto);
alter table piezas_productos
add constraint fk_piezas_productos_id_tecnico foreign key(id_tecnico) references tecnicos(id_tecnico);
*/

/*
CREATE TABLE producto_componentes (
    id_producto VARCHAR2(6) NOT NULL,
    id_pieza  VARCHAR2(6) NOT NULL,
    cantidad          NUMBER(8,2) DEFAULT 1 NOT NULL CHECK (cantidad > 0),
    CONSTRAINT pk_bom PRIMARY KEY (id_producto, id_pieza),
    CONSTRAINT fk_bom_producto FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
    CONSTRAINT fk_bom_pieza  FOREIGN KEY (id_pieza)  REFERENCES productos (id_producto),
    CONSTRAINT ch_bom_no_ciclos CHECK (id_producto <> id_pieza)
);
*/


create table ventas (
    codigo_venta varchar2(6) not null,
    fecha_venta date not null,
    valor_total number not null,
    documento_cliente varchar2(15) not null
);
alter table ventas
add constraint pk_ventas_codigo_venta primary key(codigo_venta);
alter table ventas
add constraint fk_ventas_documento_cliente foreign key(documento_cliente) references clientes(documento_cliente);


--piezas
create table piezas(
    id_pieza varchar2(6) not null, --Ej: PI-01
    nombre varchar2(20) not null,
    altura number(3,2) not null,
    ancho number(3,2) not null,
    peso number(3,2) not null,
    fecha_creacion date not null,
    valor_unitario number not null,
    documento_tecnico varchar2(15) not null,
    codigo_venta varchar2(6)
);
alter table piezas
add constraint pk_piezas_id_pieza primary key(id_pieza);
alter table piezas
add constraint fk_piezas_documento_tecnico foreign key(documento_tecnico) references tecnicos(documento_tecnico);
alter table piezas
add constraint fk_piezas_codigo_venta foreign key(codigo_venta) references ventas(codigo_venta);



create type objeto1 as object (
    campo1_obj1 number,
    campo2_obj1 number
);
/

create type objeto2 as object (
    campo1_obj2 number,
    campo2_obj2 number,
    campo3_obj2 objeto1
);
/

create table datos (
    id number,
    campo1_datos objeto2
);
alter table datos
add constraint pk_datos primary key(id);
alter table datos
add constraint nn_campo2_obj2 check(campo1_datos.campo3_obj2.campo2_obj1 is not null);


insert into datos values (1, objecto2(2, 5, objecto1(3, 4)));

--es obligación agregar un alias a la tabla en estructura de objeto
select * from datos d;


update datos d
set campo1_datos.campo3_obj2.campo1_obj1 = 10;